eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
server:
  port: 5555
spring:
  application:
    name: service-feign
# Feign中使用断路器
feign:
  hystrix:
    enabled: true